export default defineAppConfig({
  shadcnDocs: {
    site: {
      name: 'McHMR Docs',
      description: 'Beautifully designed Nuxt Content template built with shadcn-vue. Customizable. Compatible. Open Source.',
      ogImage: '/hero.png',
      ogImageComponent: 'ShadcnDocs',
      ogImageColor: 'light',
      umami: {
        enable: false,
        src: 'https://cloud.umami.is/script.js',
        dataWebsiteId: '',
      },
    },
    theme: {
      customizable: false,
      color: 'Rose',
      radius: 1,
    },
    banner: {
      enable: true,
      showClose: true,
      content: 'McHMR 快报：McHMR 团队已完全开放源代码，接受社区贡献，点击 Github 按钮查看。',
      to: '#',
      target: '_self',
      border: true,
    },
    header: {
      title: 'McHMR Docs',
      showTitle: true,
      logo: {
        light: '/logo.svg',
        dark: '/logo-dark.svg',
      },
      border: false,
      darkModeToggle: true,
      languageSwitcher: {
        enable: true,
        triggerType: 'icon',
        dropdownType: 'select',
      },
      nav: [{
        title: 'Docs',
        links: [{
          title: 'Getting Started',
          to: '/getting-started',
          description: 'Start deploying your McHMR program with McHMR-Docs.',
          icon: 'lucide:rocket',
        }, {
          title: 'Usage',
          to: '/usage/home',
          description: 'Read more about McHMR is usage guidelines.',
          icon: 'lucide:hand',
        }, {
          title: 'API',
          to: '/api/start',
          description: 'Plug the update capability into your launcher via the McHMR open API.',
          target: '_self',
          icon: 'lucide:code',
        }],
      }, {
        title: 'More',
        links: [{
          title: 'Contributing',
          to: '/contribution/standard',
          description: 'Contributing code to open-source McHMR.',
          icon: 'lucide:git-pull-request-arrow',
        }, {
          title: 'FAQ',
          to: '/blog/faq',
          description: 'Read more about McHMR frequently asked questions.',
          icon: 'lucide:badge-question-mark',
        }, {
          title: 'User Agreement',
          to: '/blog/user-agreement',
          description: 'Read more about McHMR user agreement.',
          icon: 'lucide:file-text',
        }],
      }, {
        title: 'Blog',
        to: '/blog',
        target: '_self',
        showLinkIcon: false,
      }],
      links: [
        {
          icon: 'lucide:coffee',
          to: '/blog/sponsor',
        },
        {
          icon: 'lucide:github',
          to: 'https://github.com/Lunova-Studio/mchmr-docs',
          target: '_blank',
        },
      ],
    },
    aside: {
      useLevel: true,
      levelStyle: 'aside',
      collapse: false,
      collapseLevel: 1,
      folderStyle: 'default',
    },
    main: {
      padded: true,
      breadCrumb: true,
      showTitle: true,
      codeCopyToast: false,
      codeCopyIcon: 'lucide:clipboard',
      editLink: {
        enable: true,
        pattern: 'https://github.com/Lunova-Studio/mchmr-docs/edit/main/www/content/:path',
        text: 'Edit this page',
        icon: 'lucide:square-pen',
        placement: ['docsFooter'],
      },
      backToTop: true,
      codeIcon: {
        'package.json': 'vscode-icons:file-type-node',
        'tsconfig.json': 'vscode-icons:file-type-tsconfig',
        '.npmrc': 'vscode-icons:file-type-npm',
        '.editorconfig': 'vscode-icons:file-type-editorconfig',
        '.eslintrc': 'vscode-icons:file-type-eslint',
        '.eslintrc.cjs': 'vscode-icons:file-type-eslint',
        '.eslintignore': 'vscode-icons:file-type-eslint',
        'eslint.config.js': 'vscode-icons:file-type-eslint',
        'eslint.config.mjs': 'vscode-icons:file-type-eslint',
        'eslint.config.cjs': 'vscode-icons:file-type-eslint',
        '.gitignore': 'vscode-icons:file-type-git',
        'yarn.lock': 'vscode-icons:file-type-yarn',
        '.env': 'vscode-icons:file-type-dotenv',
        '.env.example': 'vscode-icons:file-type-dotenv',
        '.vscode/settings.json': 'vscode-icons:file-type-vscode',
        'nuxt': 'vscode-icons:file-type-nuxt',
        '.nuxtrc': 'vscode-icons:file-type-nuxt',
        '.nuxtignore': 'vscode-icons:file-type-nuxt',
        'nuxt.config.js': 'vscode-icons:file-type-nuxt',
        'nuxt.config.ts': 'vscode-icons:file-type-nuxt',
        'nuxt.schema.ts': 'vscode-icons:file-type-nuxt',
        'tailwind.config.js': 'vscode-icons:file-type-tailwind',
        'tailwind.config.ts': 'vscode-icons:file-type-tailwind',
        'vue': 'vscode-icons:file-type-vue',
        'ts': 'vscode-icons:file-type-typescript',
        'tsx': 'vscode-icons:file-type-typescript',
        'mjs': 'vscode-icons:file-type-js',
        'cjs': 'vscode-icons:file-type-js',
        'js': 'vscode-icons:file-type-js',
        'jsx': 'vscode-icons:file-type-js',
        'md': 'vscode-icons:file-type-markdown',
        'mdc': 'vscode-icons:file-type-markdown',
        'css': 'vscode-icons:file-type-css',
        'py': 'vscode-icons:file-type-python',
        'npm': 'vscode-icons:file-type-npm',
        'pnpm': 'vscode-icons:file-type-pnpm',
        'npx': 'vscode-icons:file-type-npm',
        'yarn': 'vscode-icons:file-type-yarn',
        'bun': 'vscode-icons:file-type-bun',
        'yml': 'vscode-icons:file-type-light-yaml',
        'json': 'vscode-icons:file-type-json',
        'terminal': 'lucide:terminal',
      },
    },
    footer: {
      border: true,
      credits: 'FOOTER_CREDIT',
      links: [
        {
          icon: 'lucide:heart',
          title: 'Sponsor Me',
          to: '/blog/sponsor',
        },
        {
          icon: 'lucide:github',
          to: 'https://github.com/Lunova-Studio/mchmr-docs',
          target: '_blank',
        },
      ],
    },
    toc: {
      enable: true,
      enableInMobile: true,
      enableInHomepage: false,
      title: 'On this page',
      links: [
        {
          title: 'Star on GitHub',
          icon: 'lucide:star',
          to: 'https://github.com/Lunova-Studio/mchmr-docs',
          target: '_blank',
          showLinkIcon: true,
        },
        {
          title: 'Create Issues',
          icon: 'lucide:circle-dot',
          to: 'https://github.com/Lunova-Studio/mchmr-docs/issues',
          target: '_blank',
          showLinkIcon: true,
        },
      ],
      iconLinks: [
        {
          icon: 'lucide:coffee',
          to: '/blog/sponsor',
        },
      ],
      carbonAds: {
        enable: false,
        disableInDev: false,
        disableInMobile: false,
        fallback: false,
        fallbackMessage: 'Please support us by disabling your ad blocker.',
        code: 'CW7ITKJN',
        placement: 'shadcn-docs-nuxtvercelapp',
        format: 'cover',
      },
    },
    search: {
      enable: true,
      inAside: false,
      style: 'input',
    },
    data: {},
  },
});
